version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run:
          name: Install Maven and JaCoCo
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
            mvn org.jacoco:jacoco-maven-plugin:prepare-agent test

      - run:
          name: Run Unit Tests
          command: mvn test

      - persist_to_workspace:
          root: .
          paths:
            - target/site/jacoco/jacoco.xml

  upload:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  upload-to-codecov:
    jobs:
      - checkout
      - build
      - upload:
          requires:
            - build
