version: 2.1

orb:
  codecov: codecov/codecov

jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run:
          name: run
          command: mvn -B clean package

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run test
          command: mvn test
      - codecov/upload

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - build
      - test:
          requires:
            - build
