version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisation de l'image Docker avec Java 8

    branches:
      only:
        - origin/master  # Branche master uniquement

    steps:
      - checkout  # Récupération du code source du repository

      # Installation de Maven
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test
