version: 2.1

jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run:
          name: run
          command: mvn -B -DskipTests clean package

  upload:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - build
      - upload:
          requires:
            - build
