version: 2.1

jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run:
          name: Install Maven and JaCoCo
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
            mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install

  upload:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - upload:
          requires:
            - build
