version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Run Unit Tests
          command: mvn test

  upload:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - upload:
          requires:
            - build
