version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:

  build:
    docker:
      - image: cimg/openjdk:8.0

    steps:
      - checkout
      - run:
          name: run
          command: mvn -B clean package

  test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Run test
          command: mvn test
      - run:
          name: code coveraging
          command: mvn jacoco:report
      - codecov/upload

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - build
      - test:
          requires:
            - build
