version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:

  build:
    docker:
      - image: cimg/openjdk:8.0

    steps:
      - checkout
      - run:
          name: run
          command: mvn -B clean package
      - run: mvn --version
      - run: mvn test


  test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      -  run:
          name: Build with Maven and run tests
          command: mvn clean verify

      - run:
          name: Generate JaCoCo report
          command: mvn jacoco:report
      - codecov/upload

workflows:
  upload-to-codecov:
    jobs:
      - build
      - test:
          requires:
            - build
