version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:

  build:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run: mvn verify


  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      -  run:
          name: Build with Maven and run tests
          command: mvn clean verify

      - run:
          name: Generate JaCoCo report
          command: mvn jacoco:report
      - codecov/upload:
          token: 6b916898-52fa-4c42-81bf-15bcc6e17bfe

workflows:
  upload-to-codecov:
    jobs:
      - build
      - test:
          requires:
            - build
