version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
  codecov/upload:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisation de l'image Docker avec Java 8

    steps:
      - checkout  # Récupération du code source du repository

      # Installation de Maven
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test

orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload